// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const header: string;
export const headerTitle: string;
export const panelContent: string;
export const headerText: string;
export const conceptDiagramExplanation: string;
export const collapsibleContent: string;
export const textAlignRight: string;
