version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: project
        must_include:
          regex: '20\.8\.0|20\.9\.0'
          message: 'Project must be specified'

    pass:
      - do: checks
        status: 'success'
