version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: project
        no_empty:
          enabled: true
          message: "Project must be specified"
        must_include:
          # one or more chars
          regex: '.+'
          message: "Project must be specified"
