// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const tasksContainer: string;
export const tasksListContainer: string;
export const taskDescriptionContainer: string;
export const execTaskDescriptionContainer: string;
export const commandSection: string;
export const execEditor: string;
